/**
 * Brands Data for Detail Pages
 * Contains all brand information for generating unique detail pages
 */

export const BRANDS_DATA = [
  {
    id: 'apollo-life',
    name: 'Apollo Life',
    tagline: 'Quality You Can Trust',
    icon: 'medical-outline',
    color: '#E8F5E9',
    gradColors: ['#0F847E', '#0A6B66'],
    products: 250,
    rating: 4.8,
    category: 'pharma',
    featured: true,
    exclusive: true,
    description: 'Apollo Life brings you premium health and wellness products crafted with the highest quality standards. Trusted by millions across India.',
    bannerImage: 'apollo_life_banner',
    features: ['Quality Assured', 'Doctor Recommended', 'Wide Range'],
    highlights: ['No. 1 Pharmacy Brand', 'Trusted by 50L+ Customers', '100% Authentic'],
    products: [
      { id: 'al1', name: 'Apollo Life Multivitamin', price: 599, mrp: 799, rating: 4.7, discount: '25% OFF', category: 'Supplements' },
      { id: 'al2', name: 'Apollo Life Vitamin D3', price: 120, mrp: 150, rating: 4.8, discount: '20% OFF', category: 'Supplements' },
      { id: 'al3', name: 'Apollo Life Fish Oil', price: 349, mrp: 450, rating: 4.6, discount: '22% OFF', category: 'Supplements' },
      { id: 'al4', name: 'Apollo Life Calcium', price: 180, mrp: 220, rating: 4.7, discount: '18% OFF', category: 'Supplements' },
      { id: 'al5', name: 'Apollo Life Immunity', price: 299, mrp: 399, rating: 4.8, discount: '25% OFF', category: 'Supplements' },
    ],
    about: 'Apollo Life is a trusted brand from the house of Apollo Hospitals, committed to delivering quality healthcare products. With decades of expertise in healthcare, Apollo Life offers a wide range of supplements, wellness products, and health devices.',
    faqs: [
      { q: 'Are Apollo Life products authentic?', a: 'Yes, 100% authentic with quality assurance.' },
      { q: 'Do Apollo Life products have side effects?', a: 'No, when taken as recommended.' },
    ],
  },
  {
    id: 'himalaya',
    name: 'Himalaya',
    tagline: 'Pure Herbs, Pure Care',
    icon: 'leaf-outline',
    color: '#E8F5E9',
    gradColors: ['#22C55E', '#16A34A'],
    products: 180,
    rating: 4.7,
    category: 'ayurveda',
    featured: true,
    exclusive: false,
    description: 'Himalaya offers Ayurvedic and herbal products that combine traditional wisdom with modern science. Gentle yet effective solutions for your health.',
    bannerImage: 'himalaya_banner',
    features: ['Ayurvedic Formulation', 'No Side Effects', 'Natural Ingredients'],
    highlights: ['95+ Years of Legacy', 'Global Presence', 'Research Backed'],
    products: [
      { id: 'h1', name: 'Liv.52 Tablets', price: 180, mrp: 220, rating: 4.8, discount: '18% OFF', category: 'Liver Care' },
      { id: 'h2', name: 'Ashwagandha', price: 250, mrp: 320, rating: 4.7, discount: '21% OFF', category: 'Stress Relief' },
      { id: 'h3', name: 'Brahmi', price: 180, mrp: 220, rating: 4.6, discount: '18% OFF', category: 'Brain Health' },
      { id: 'h4', name: 'Gymnema Sylvestre', price: 150, mrp: 180, rating: 4.5, discount: '16% OFF', category: 'Diabetes' },
      { id: 'h5', name: 'Neem Capsules', price: 120, mrp: 150, rating: 4.6, discount: '20% OFF', category: 'Skin Care' },
    ],
    about: 'Founded in 1930, Himalaya is a pioneer in Ayurvedic medicines and personal care products. Their products are formulated using herbs and natural ingredients, backed by clinical research.',
    faqs: [
      { q: 'Are Himalaya products safe?', a: 'Yes, made from natural ingredients with no harmful chemicals.' },
      { q: 'Can Himalaya products be taken with allopathy?', a: 'Generally safe, but consult doctor for specific products.' },
    ],
  },
  {
    id: 'cipla',
    name: 'Cipla',
    tagline: 'Caring for Life',
    icon: 'medical-outline',
    color: '#E3F2FD',
    gradColors: ['#3B82F6', '#2563EB'],
    products: 320,
    rating: 4.9,
    category: 'pharma',
    featured: true,
    exclusive: false,
    description: 'Cipla is a global pharmaceutical company dedicated to delivering high-quality, affordable medicines. Trusted by doctors and patients worldwide.',
    bannerImage: 'cipla_banner',
    features: ['Quality Medicines', 'Affordable Pricing', 'Global Standards'],
    highlights: ['80+ Years of Trust', 'Global Pharmaceutical Leader', '150+ Countries'],
    products: [
      { id: 'c1', name: 'Azithromycin 500mg', price: 67, mrp: 79, rating: 4.7, discount: '15% OFF', category: 'Antibiotics' },
      { id: 'c2', name: 'Amoxicillin 500mg', price: 89, mrp: 105, rating: 4.6, discount: '15% OFF', category: 'Antibiotics' },
      { id: 'c3', name: 'Ciprofloxacin 500mg', price: 45, mrp: 55, rating: 4.7, discount: '18% OFF', category: 'Antibiotics' },
      { id: 'c4', name: 'Cetirizine 10mg', price: 25, mrp: 32, rating: 4.6, discount: '21% OFF', category: 'Allergy' },
      { id: 'c5', name: 'Montair 10mg', price: 120, mrp: 150, rating: 4.8, discount: '20% OFF', category: 'Allergy' },
    ],
    about: 'Cipla is a leading global pharmaceutical company with a presence in over 150 countries. Known for making life-saving drugs accessible and affordable.',
    faqs: [
      { q: 'Are Cipla products FDA approved?', a: 'Yes, Cipla follows global quality standards.' },
      { q: 'Where are Cipla products manufactured?', a: 'In WHO-GMP certified facilities in India.' },
    ],
  },
  {
    id: 'sun-pharma',
    name: 'Sun Pharma',
    tagline: 'Reaching People, Touching Lives',
    icon: 'sunny-outline',
    color: '#FFF3E0',
    gradColors: ['#F97316', '#EA580C'],
    products: 290,
    rating: 4.7,
    category: 'pharma',
    featured: true,
    exclusive: false,
    description: 'Sun Pharma is one of the largest pharmaceutical companies in India, offering a wide range of generic medicines and specialty products.',
    bannerImage: 'sun_pharma_banner',
    features: ['Generic Medicines', 'Specialty Products', 'Global Reach'],
    highlights: ['No. 1 in India', '150+ Countries', 'Innovation Leader'],
    products: [
      { id: 'sp1', name: 'Pantoprazole 40mg', price: 85, mrp: 100, rating: 4.7, discount: '15% OFF', category: 'Gastric' },
      { id: 'sp2', name: 'Volini Spray', price: 179, mrp: 250, rating: 4.8, discount: '28% OFF', category: 'Pain Relief' },
      { id: 'sp3', name: 'Rosuvastatin 10mg', price: 180, mrp: 220, rating: 4.6, discount: '18% OFF', category: 'Cholesterol' },
      { id: 'sp4', name: 'Mirtaz 15mg', price: 120, mrp: 150, rating: 4.7, discount: '20% OFF', category: 'Mental Health' },
      { id: 'sp5', name: 'Isotretinoin 20mg', price: 250, mrp: 320, rating: 4.5, discount: '21% OFF', category: 'Skin Care' },
    ],
    about: 'Sun Pharmaceutical Industries is an Indian multinational pharmaceutical company headquartered in Mumbai. It is the largest pharmaceutical company in India.',
    faqs: [
      { q: 'Are Sun Pharma products affordable?', a: 'Yes, known for affordable generic medicines.' },
      { q: 'Is Sun Pharma trustworthy?', a: 'Absolutely, one of India\'s most trusted pharmaceutical companies.' },
    ],
  },
  {
    id: 'dabur',
    name: 'Dabur',
    tagline: 'Celebrate Life',
    icon: 'flask-outline',
    color: '#E8F5E9',
    gradColors: ['#84CC16', '#65A30D'],
    products: 200,
    rating: 4.6,
    category: 'ayurveda',
    featured: true,
    exclusive: false,
    description: 'Dabur is India\'s leading Ayurvedic and natural health care company with a legacy of over 135 years. Natural solutions for modern health needs.',
    bannerImage: 'dabur_banner',
    features: ['Ayurvedic Heritage', 'Natural Ingredients', 'Trusted Quality'],
    highlights: ['135+ Years Legacy', 'No. 1 Ayurvedic Brand', 'Global Presence'],
    products: [
      { id: 'db1', name: 'Chyawanprash', price: 350, mrp: 450, rating: 4.9, discount: '22% OFF', category: 'Immunity' },
      { id: 'db2', name: 'Triphala Churna', price: 120, mrp: 150, rating: 4.6, discount: '20% OFF', category: 'Digestive' },
      { id: 'db3', name: 'Dabur Honitus', price: 80, mrp: 100, rating: 4.7, discount: '20% OFF', category: 'Cough & Cold' },
      { id: 'db4', name: 'Dabur Pudin Hara', price: 35, mrp: 45, rating: 4.8, discount: '22% OFF', category: 'Digestive' },
      { id: 'db5', name: 'Dabur Lal Tail', price: 90, mrp: 110, rating: 4.5, discount: '18% OFF', category: 'Baby Care' },
    ],
    about: 'Dabur India Ltd is the largest Ayurvedic and natural health care company in the world. It offers a wide range of products for health, wellness, and personal care.',
    faqs: [
      { q: 'Are Dabur products purely natural?', a: 'Yes, made from natural ingredients and herbs.' },
      { q: 'Can children use Dabur products?', a: 'Yes, there are specific products for children.' },
    ],
  },
  {
    id: 'mamaearth',
    name: 'Mamaearth',
    tagline: 'Goodness Inside',
    icon: 'globe-outline',
    color: '#FCE4EC',
    gradColors: ['#EC4899', '#DB2777'],
    products: 120,
    rating: 4.5,
    category: 'personal',
    featured: true,
    exclusive: false,
    description: 'Mamaearth is India\'s first toxin-free, natural baby and beauty brand. Safe products for you and your family.',
    bannerImage: 'mamaearth_banner',
    features: ['Toxin Free', 'Natural Ingredients', 'Dermat Tested'],
    highlights: ['Asia\'s First B Corp Certified', 'Cruelty Free', 'Made Safe Certified'],
    products: [
      { id: 'me1', name: 'Onion Hair Oil', price: 349, mrp: 449, rating: 4.7, discount: '22% OFF', category: 'Hair Care' },
      { id: 'me2', name: 'Vitamin C Face Serum', price: 399, mrp: 499, rating: 4.6, discount: '20% OFF', category: 'Skin Care' },
      { id: 'me3', name: 'Ubtan Face Wash', price: 249, mrp: 320, rating: 4.5, discount: '22% OFF', category: 'Skin Care' },
      { id: 'me4', name: 'Body Butter', price: 449, mrp: 599, rating: 4.7, discount: '25% OFF', category: 'Body Care' },
      { id: 'me5', name: 'Baby Massage Oil', price: 299, mrp: 399, rating: 4.8, discount: '25% OFF', category: 'Baby Care' },
    ],
    about: 'Mamaearth is a Purpose-driven brand focused on providing toxin-free, natural, and cruelty-free products for babies and adults.',
    faqs: [
      { q: 'Are Mamaearth products safe for sensitive skin?', a: 'Yes, dermatologically tested and gentle.' },
      { q: 'Are Mamaearth products cruelty-free?', a: '100% cruelty-free and vegan.' },
    ],
  },
  {
    id: 'abbott',
    name: 'Abbott',
    tagline: 'Life. To the Fullest.',
    icon: 'medical-outline',
    color: '#E3F2FD',
    gradColors: ['#3B82F6', '#2563EB'],
    products: 180,
    rating: 4.8,
    category: 'pharma',
    featured: false,
    exclusive: false,
    description: 'Abbott is a global healthcare leader with a diverse portfolio of life-changing products in diagnostics, medical devices, nutrition, and branded generic medicines.',
    bannerImage: 'abbott_banner',
    features: ['Global Quality', 'Innovation Driven', 'Trusted Worldwide'],
    highlights: ['130+ Years of Innovation', 'Global Presence', '100,000+ Employees'],
    products: [
      { id: 'ab1', name: 'Ensure Diabetes Care', price: 699, mrp: 920, rating: 4.7, discount: '24% OFF', category: 'Nutrition' },
      { id: 'ab2', name: 'Ensure High Protein', price: 599, mrp: 799, rating: 4.8, discount: '25% OFF', category: 'Nutrition' },
      { id: 'ab3', name: 'Pediasure', price: 450, mrp: 550, rating: 4.7, discount: '18% OFF', category: 'Nutrition' },
      { id: 'ab4', name: 'Digene Gel', price: 90, mrp: 120, rating: 4.6, discount: '25% OFF', category: 'Digestive' },
      { id: 'ab5', name: 'Phytase-AD', price: 180, mrp: 220, rating: 4.5, discount: '18% OFF', category: 'Digestive' },
    ],
    about: 'Abbott is a global healthcare company that helps people live fully through life-changing technologies in diagnostics, medical devices, nutrition, and branded generic medicines.',
    faqs: [
      { q: 'Is Abbott a trusted brand?', a: 'One of the most trusted global healthcare companies.' },
      { q: 'Are Abbott products available in India?', a: 'Yes, widely available across India.' },
    ],
  },
  {
    id: 'dr-morepen',
    name: 'Dr. Morepen',
    tagline: 'Your Family Health Partner',
    icon: 'medkit-outline',
    color: '#E3F2FD',
    gradColors: ['#3B82F6', '#2563EB'],
    products: 80,
    rating: 4.5,
    category: 'wellness',
    featured: false,
    exclusive: false,
    description: 'Dr. Morepen offers a wide range of healthcare products including diagnostic devices, daily health supplements, and wellness products.',
    bannerImage: 'morepen_banner',
    features: ['Diagnostic Devices', 'Daily Health', 'Wellness Solutions'],
    highlights: ['Home Diagnostics', 'Easy to Use', 'Affordable'],
    products: [
      { id: 'dm1', name: 'BP Monitor', price: 899, mrp: 1199, rating: 4.6, discount: '25% OFF', category: 'Devices' },
      { id: 'dm2', name: 'Glucometer', price: 399, mrp: 499, rating: 4.5, discount: '20% OFF', category: 'Devices' },
      { id: 'dm3', name: 'Pulse Oximeter', price: 499, mrp: 699, rating: 4.7, discount: '28% OFF', category: 'Devices' },
      { id: 'dm4', name: 'Morepen Multivitamin', price: 199, mrp: 250, rating: 4.4, discount: '20% OFF', category: 'Supplements' },
      { id: 'dm5', name: 'Pain Relief Spray', price: 149, mrp: 180, rating: 4.5, discount: '17% OFF', category: 'Pain Relief' },
    ],
    about: 'Dr. Morepen is a part of Morepen Laboratories, committed to providing quality healthcare products for every home.',
    faqs: [
      { q: 'Are Dr. Morepen devices accurate?', a: 'Yes, clinically validated for accuracy.' },
    ],
  },
  {
    id: 'ensure',
    name: 'Ensure',
    tagline: 'Complete Nutrition',
    icon: 'nutrition-outline',
    color: '#FFF3E0',
    gradColors: ['#F97316', '#EA580C'],
    products: 25,
    rating: 4.7,
    category: 'nutrition',
    featured: false,
    exclusive: false,
    description: 'Ensure is the #1 brand of complete, balanced nutritional supplements recommended by doctors worldwide for adults.',
    bannerImage: 'ensure_banner',
    features: ['Complete Nutrition', 'Doctor Recommended', 'Scientifically Formulated'],
    highlights: ['#1 Nutritional Brand', '30+ Years of Trust', '30+ Countries'],
    products: [
      { id: 'en1', name: 'Ensure Diabetes Care', price: 699, mrp: 920, rating: 4.7, discount: '24% OFF', category: 'Diabetes' },
      { id: 'en2', name: 'Ensure High Protein', price: 599, mrp: 799, rating: 4.8, discount: '25% OFF', category: 'Protein' },
      { id: 'en3', name: 'Ensure Original', price: 549, mrp: 699, rating: 4.7, discount: '21% OFF', category: 'Nutrition' },
      { id: 'en4', name: 'Ensure Plus', price: 650, mrp: 850, rating: 4.6, discount: '23% OFF', category: 'Nutrition' },
    ],
    about: 'Ensure provides complete, balanced nutrition to help adults stay healthy, active, and energetic. Recommended by healthcare professionals worldwide.',
    faqs: [
      { q: 'Can I replace meals with Ensure?', a: 'It can supplement diet but consult doctor for meal replacement.' },
    ],
  },
  {
    id: 'patanjali',
    name: 'Patanjali',
    tagline: 'Swadeshi Swasthya',
    icon: 'leaf-outline',
    color: '#F1F8E9',
    gradColors: ['#22C55E', '#16A34A'],
    products: 150,
    rating: 4.3,
    category: 'ayurveda',
    featured: false,
    exclusive: false,
    description: 'Patanjali is India\'s largest FMCG company offering authentic Ayurvedic products at affordable prices. Pure and natural solutions.',
    bannerImage: 'patanjali_banner',
    features: ['Ayurvedic Products', 'Affordable Pricing', 'Swadeshi Quality'],
    highlights: ['Largest FMCG in India', 'Authentic Ayurveda', 'Budget Friendly'],
    products: [
      { id: 'pt1', name: 'Patanjali Aloe Vera Gel', price: 145, mrp: 180, rating: 4.4, discount: '19% OFF', category: 'Skin Care' },
      { id: 'pt2', name: 'Patanjali Divya Peytu', price: 35, mrp: 45, rating: 4.5, discount: '22% OFF', category: 'Digestive' },
      { id: 'pt3', name: 'Patanjali Chyawanprash', price: 280, mrp: 350, rating: 4.5, discount: '20% OFF', category: 'Immunity' },
      { id: 'pt4', name: 'Patanjali Face Wash', price: 80, mrp: 100, rating: 4.3, discount: '20% OFF', category: 'Skin Care' },
      { id: 'pt5', name: 'Patanjali Dant Kanti', price: 65, mrp: 80, rating: 4.4, discount: '18% OFF', category: 'Oral Care' },
    ],
    about: 'Patanjali is India\'s leading Ayurvedic and natural product company founded by Acharya Balkrishna. Known for authentic Ayurveda at affordable prices.',
    faqs: [
      { q: 'Are Patanjali products purely natural?', a: 'Yes, made from Ayurvedic ingredients.' },
    ],
  },
];

export const getBrandById = (id) => {
  return BRANDS_DATA.find(brand => brand.id === id);
};

export const getAllBrands = () => {
  return BRANDS_DATA;
};
