/**
 * Category Data for Detail Pages
 * Contains all category information for generating unique detail pages
 */

export const CATEGORIES_DATA = [
  {
    id: 'wellness',
    name: 'Wellness',
    icon: 'heart-outline',
    color: '#E8F5E9',
    gradColors: ['#22C55E', '#16A34A'],
    count: 450,
    description: 'Discover premium wellness products to support your healthy lifestyle. From vitamins to supplements, we have everything for your wellbeing.',
    bannerImage: 'wellness_banner',
    features: ['100% Authentic Products', 'Free Health Consultation', 'Express Delivery'],
    products: [
      { id: 'w1', name: 'Multivitamin Gold', brand: 'Apollo Life', price: 599, mrp: 799, rating: 4.7, discount: '25% OFF' },
      { id: 'w2', name: 'Omega 3 Fish Oil', brand: 'Himalaya', price: 349, mrp: 499, rating: 4.5, discount: '30% OFF' },
      { id: 'w3', name: 'Vitamin D3 60K', brand: 'USV', price: 120, mrp: 150, rating: 4.9, discount: '20% OFF' },
      { id: 'w4', name: 'Immunity Booster', brand: 'Dabur', price: 250, mrp: 350, rating: 4.6, discount: '28% OFF' },
      { id: 'w5', name: 'Protein Whey', brand: 'Ensure', price: 899, mrp: 1199, rating: 4.8, discount: '25% OFF' },
    ],
    subCategories: ['Vitamins & Supplements', 'Immunity Boosters', 'Digestive Health', 'Heart Health', 'Bone & Joint'],
    tips: ['Take vitamins with food for better absorption', 'Maintain consistent timing for supplements', 'Stay hydrated while taking supplements'],
    faqs: [
      { q: 'Are wellness products safe to use daily?', a: 'Yes, when taken as recommended. Consult doctor for personalized advice.' },
      { q: 'Can I take multiple supplements together?', a: 'Some supplements may interact. Consult healthcare provider.' },
    ],
  },
  {
    id: 'personal-care',
    name: 'Personal Care',
    icon: 'person-outline',
    color: '#E3F2FD',
    gradColors: ['#3B82F6', '#2563EB'],
    count: 380,
    description: 'Explore our extensive range of personal care products for your daily hygiene and grooming needs. Premium quality for all skin types.',
    bannerImage: 'personal_care_banner',
    features: ['Dermatologically Tested', 'For All Skin Types', 'Cruelty Free'],
    products: [
      { id: 'pc1', name: 'Cetaphil Cleanser', brand: 'Galderma', price: 399, mrp: 549, rating: 4.8, discount: '27% OFF' },
      { id: 'pc2', name: 'Neutrogena Sunscreen', brand: 'Johnson', price: 499, mrp: 699, rating: 4.6, discount: '28% OFF' },
      { id: 'pc3', name: 'CeraVe Moisturizer', brand: 'L\'Oreal', price: 599, mrp: 799, rating: 4.7, discount: '25% OFF' },
      { id: 'pc4', name: 'L\'Oreal Shampoo', brand: 'L\'Oreal', price: 299, mrp: 399, rating: 4.5, discount: '25% OFF' },
      { id: 'pc5', name: 'Colgate Toothpaste', brand: 'Colgate', price: 149, mrp: 180, rating: 4.7, discount: '17% OFF' },
    ],
    subCategories: ['Skin Care', 'Hair Care', 'Oral Care', 'Bath & Body', 'Fragrances'],
    tips: ['Choose products suitable for your skin type', 'Patch test new products before regular use', 'Maintain consistent skincare routine'],
    faqs: [
      { q: 'How to choose right skincare products?', a: 'Know your skin type and look for products formulated for it.' },
      { q: 'Are expensive products always better?', a: 'Not necessarily. Focus on ingredients and your skin needs.' },
    ],
  },
  {
    id: 'nutrition',
    name: 'Nutrition',
    icon: 'nutrition-outline',
    color: '#FFF3E0',
    gradColors: ['#F97316', '#EA580C'],
    count: 290,
    description: 'Fuel your body with premium nutritional products. From protein powders to health drinks, find everything for your nutritional needs.',
    bannerImage: 'nutrition_banner',
    features: ['Scientifically Formulated', 'Free Delivery', 'Best Prices'],
    products: [
      { id: 'n1', name: 'Ensure Diabetes Care', brand: 'Abbott', price: 699, mrp: 920, rating: 4.6, discount: '24% OFF' },
      { id: 'n2', name: 'Protinex T额外', brand: 'Danone', price: 449, mrp: 625, rating: 4.5, discount: '28% OFF' },
      { id: 'n3', name: 'Complan Nutrition', brand: 'Nestle', price: 299, mrp: 399, rating: 4.4, discount: '25% OFF' },
      { id: 'n4', name: 'Horlicks J无', brand: 'GSK', price: 249, mrp: 320, rating: 4.5, discount: '22% OFF' },
      { id: 'n5', name: 'Protein Bar', brand: 'Fast&Up', price: 199, mrp: 299, rating: 4.7, discount: '33% OFF' },
    ],
    subCategories: ['Protein Powders', 'Health Drinks', 'Nutritional Supplements', 'Weight Management', 'Sports Nutrition'],
    tips: ['Choose protein based on your activity level', 'Check sugar content in health drinks', 'Consult nutritionist for personalized plan'],
    faqs: [
      { q: 'When is best time to take protein?', a: 'Within 30 minutes post-workout or with breakfast.' },
      { q: 'Are protein powders safe?', a: 'Yes, when used as directed. Choose quality brands.' },
    ],
  },
  {
    id: 'baby-care',
    name: 'Baby Care',
    icon: 'happy-outline',
    color: '#FCE4EC',
    gradColors: ['#EC4899', '#DB2777'],
    count: 210,
    description: 'Everything your little one needs. From baby food to diapers, we have premium products for your baby\'s growth and development.',
    bannerImage: 'baby_care_banner',
    features: ['Baby Safe Products', 'Pediatrician Recommended', 'Fast Delivery'],
    products: [
      { id: 'b1', name: 'Huggies Diapers', brand: 'Kimberly', price: 799, mrp: 999, rating: 4.8, discount: '20% OFF' },
      { id: 'b2', name: 'Pampers Diapers', brand: 'P&G', price: 899, mrp: 1199, rating: 4.7, discount: '25% OFF' },
      { id: 'b3', name: 'Cerelac Stage 3', brand: 'Nestle', price: 299, mrp: 350, rating: 4.6, discount: '14% OFF' },
      { id: 'b4', name: 'Enfamil Stage 1', brand: 'Mead Johnson', price: 399, mrp: 499, rating: 4.8, discount: '20% OFF' },
      { id: 'b5', name: 'Johnson\'s Baby Oil', brand: 'Johnson', price: 149, mrp: 180, rating: 4.5, discount: '17% OFF' },
    ],
    subCategories: ['Diapers', 'Baby Food', 'Baby Skin Care', 'Feeding Bottles', 'Baby Toys'],
    tips: ['Choose diapers based on baby weight', 'Check age suitability for baby food', 'Maintain hygiene in baby products'],
    faqs: [
      { q: 'Which diaper brand is best?', a: 'Depends on baby\'s skin sensitivity. Try different brands.' },
      { q: 'When to start solid food?', a: 'Usually after 6 months as per pediatrician advice.' },
    ],
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: 'barbell-outline',
    color: '#F3E5F5',
    gradColors: ['#8B5CF6', '#7C3AED'],
    count: 320,
    description: 'Achieve your fitness goals with our premium fitness products. From gym supplements to fitness equipment, we have it all.',
    bannerImage: 'fitness_banner',
    features: ['Genuine Products', 'Easy Returns', 'Expert Support'],
    products: [
      { id: 'f1', name: 'MuscleBlaze Whey', brand: 'MB', price: 1299, mrp: 1799, rating: 4.7, discount: '27% OFF' },
      { id: 'f2', name: 'Optimum Nutrition', brand: 'ON', price: 2499, mrp: 3299, rating: 4.9, discount: '24% OFF' },
      { id: 'f3', name: 'MyProtein Whey', brand: 'MyProtein', price: 1799, mrp: 2499, rating: 4.6, discount: '28% OFF' },
      { id: 'f4', name: 'GNC Creatine', brand: 'GNC', price: 899, mrp: 1199, rating: 4.5, discount: '25% OFF' },
      { id: 'f5', name: 'Dymatize ISO100', brand: 'Dymatize', price: 2199, mrp: 2999, rating: 4.8, discount: '26% OFF' },
    ],
    subCategories: ['Whey Protein', 'Pre-Workout', 'Creatine', 'BCAA', 'Fitness Equipment'],
    tips: ['Assess your fitness goal before buying supplements', 'Stay consistent with workout and nutrition', 'Consult trainer for personalized plan'],
    faqs: [
      { q: 'Which protein is best for beginners?', a: 'Whey protein isolate or blend works well for most.' },
      { q: 'Do I need pre-workout supplements?', a: 'Not mandatory but can enhance performance.' },
    ],
  },
  {
    id: 'sexual-wellness',
    name: 'Sexual Wellness',
    icon: 'shield-outline',
    color: '#E8EAF6',
    gradColors: ['#6366F1', '#4F46E5'],
    count: 150,
    description: 'Shop premium sexual wellness products discreetly. From contraceptives to supplements, find solutions for your intimate health.',
    bannerImage: 'sexual_wellness_banner',
    features: ['100% Discreet Delivery', 'Authentic Products', 'Expert Consultation'],
    products: [
      { id: 's1', name: 'Durex Condoms', brand: 'Reckitt', price: 150, mrp: 200, rating: 4.7, discount: '25% OFF' },
      { id: 's2', name: 'Manforce Condoms', brand: 'Mankind', price: 120, mrp: 150, rating: 4.5, discount: '20% OFF' },
      { id: 's3', name: 'Prega News', brand: 'Mankind', price: 50, mrp: 60, rating: 4.8, discount: '16% OFF' },
      { id: 's4', name: 'Staylong Spray', brand: 'Diana', price: 299, mrp: 399, rating: 4.3, discount: '25% OFF' },
      { id: 's5', name: 'Passion Plus', brand: 'Himalaya', price: 249, mrp: 320, rating: 4.4, discount: '22% OFF' },
    ],
    subCategories: ['Condoms', 'Contraceptives', 'Intimate Care', 'Fertility Products', 'Libido Boosters'],
    tips: ['Always use protection for safe sex', 'Check expiration dates on contraceptives', 'Consult doctor for sexual health issues'],
    faqs: [
      { q: 'Are online condoms reliable?', a: 'Yes, from trusted pharmacies like ours.' },
      { q: 'How to improve intimate health?', a: 'Maintain hygiene, healthy lifestyle, and regular checkups.' },
    ],
  },
  {
    id: 'elderly-care',
    name: 'Elderly Care',
    icon: 'accessibility-outline',
    color: '#E0F2F1',
    gradColors: ['#14B8A6', '#0D9488'],
    count: 180,
    description: 'Premium products for senior citizens. From daily essentials to medical devices, care for your elders with love.',
    bannerImage: 'elderly_care_banner',
    features: ['Easy to Use Products', 'Senior Friendly', 'Quick Delivery'],
    products: [
      { id: 'e1', name: 'BP Monitor', brand: 'Omron', price: 1499, mrp: 1999, rating: 4.7, discount: '25% OFF' },
      { id: 'e2', name: 'Glucometer', brand: 'Accu-Chek', price: 599, mrp: 799, rating: 4.6, discount: '25% OFF' },
      { id: 'e3', name: 'Walker', brand: 'Dynamed', price: 899, mrp: 1199, rating: 4.5, discount: '25% OFF' },
      { id: 'e4', name: 'Wheelchair', brand: 'Karma', price: 3999, mrp: 4999, rating: 4.6, discount: '20% OFF' },
      { id: 'e5', name: 'Calcium Tablet', brand: 'Shelcal', price: 115, mrp: 135, rating: 4.7, discount: '15% OFF' },
    ],
    subCategories: ['Medical Devices', 'Daily Care', 'Mobility Aids', 'Nutritional Supplements', 'Pain Management'],
    tips: ['Regular health checkups for seniors', 'Choose easy-to-use medical devices', 'Ensure proper dosage of supplements'],
    faqs: [
      { q: 'What medical devices seniors need?', a: 'BP monitor, glucometer, pulse oximeter are essential.' },
      { q: 'How often should elderly check health?', a: 'Regular monitoring as advised by doctor.' },
    ],
  },
  {
    id: 'ayurveda',
    name: 'Ayurveda',
    icon: 'leaf-outline',
    color: '#F1F8E9',
    gradColors: ['#84CC16', '#65A30D'],
    count: 260,
    description: 'Discover the power of Ayurveda with our authentic herbal products. Traditional wisdom meets modern quality standards.',
    bannerImage: 'ayurveda_banner',
    features: ['100% Natural', 'No Side Effects', 'Authentic Herbs'],
    products: [
      { id: 'a1', name: 'Liv.52 Tablets', brand: 'Himalaya', price: 180, mrp: 220, rating: 4.7, discount: '18% OFF' },
      { id: 'a2', name: 'Ashwagandha', brand: 'Himalaya', price: 250, mrp: 320, rating: 4.6, discount: '21% OFF' },
      { id: 'a3', name: 'Triphala Churna', brand: 'Dabur', price: 120, mrp: 150, rating: 4.5, discount: '20% OFF' },
      { id: 'a4', name: 'Chyawanprash', brand: 'Dabur', price: 350, mrp: 450, rating: 4.8, discount: '22% OFF' },
      { id: 'a5', name: 'Brahmi Churna', brand: 'Patanjali', price: 150, mrp: 180, rating: 4.4, discount: '16% OFF' },
    ],
    subCategories: ['Herbal Supplements', 'Ayurvedic Medicines', 'Herbal Skin Care', 'Detox Products', 'Immunity Boosters'],
    tips: ['Follow recommended dosage', 'Consult Ayurvedic practitioner', 'Be patient with results'],
    faqs: [
      { q: 'Are Ayurvedic products safe?', a: 'Yes, when from trusted brands and taken as directed.' },
      { q: 'How long to see Ayurvedic results?', a: 'Depends on condition, usually 2-3 months.' },
    ],
  },
];

export const getCategoryById = (id) => {
  return CATEGORIES_DATA.find(cat => cat.id === id);
};

export const getAllCategories = () => {
  return CATEGORIES_DATA;
};
