/**
 * Concerns Data for Detail Pages
 * Contains all health concern information for generating unique detail pages
 */

export const CONCERNS_DATA = [
  {
    id: 'diabetes-care',
    name: 'Diabetes Care',
    icon: 'water-outline',
    color: '#E3F2FD',
    bgColor: '#1565C0',
    products: 120,
    desc: 'Monitor & manage blood sugar',
    type: 'chronic',
    description: 'Complete diabetes management solutions including blood sugar monitors, medicines, and lifestyle products. Keep your diabetes under control with our comprehensive range.',
    bannerImage: 'diabetes_banner',
    features: ['Blood Glucose Monitoring', 'Diabetes Medicines', 'Diet Planning', 'Expert Support'],
    products: [
      { id: 'd1', name: 'Glucometer Accu-Chek', brand: 'Roche', price: 599, mrp: 799, rating: 4.7, discount: '25% OFF' },
      { id: 'd2', name: 'Metformin 500mg', brand: 'USV', price: 25, mrp: 32, rating: 4.7, discount: '21% OFF' },
      { id: 'd3', name: 'Glucose Strips 50s', brand: 'Accu-Chek', price: 350, mrp: 450, rating: 4.6, discount: '22% OFF' },
      { id: 'd4', name: 'Glucometer OneTouch', brand: 'LifeScan', price: 699, mrp: 899, rating: 4.7, discount: '22% OFF' },
      { id: 'd5', name: 'Janumet 50/500', brand: 'MSD', price: 450, mrp: 550, rating: 4.8, discount: '18% OFF' },
      { id: 'd6', name: 'Insulin Glargine', brand: 'Lantus', price: 850, mrp: 1000, rating: 4.9, discount: '15% OFF' },
    ],
    tips: [
      'Monitor blood sugar regularly',
      'Follow a balanced diet low in sugar and carbs',
      'Exercise regularly to maintain weight',
      'Take medicines as prescribed',
    ],
    expertTips: [
      { title: 'Managing Blood Sugar Through Diet', readTime: '5 min', category: 'Nutrition' },
      { title: 'Understanding HbA1c Results', readTime: '4 min', category: 'Diagnosis' },
      { title: 'Exercise Guidelines for Diabetics', readTime: '6 min', category: 'Fitness' },
    ],
    faqs: [
      { q: 'What is normal blood sugar level?', a: 'Fasting: 70-100 mg/dL, Post-meal: less than 180 mg/dL' },
      { q: 'How often should I check blood sugar?', a: 'Depends on your treatment. Consult your doctor.' },
      { q: 'Can diabetes be cured?', a: 'Type 2 diabetes can be managed effectively with lifestyle changes.' },
    ],
  },
  {
    id: 'heart-health',
    name: 'Heart Health',
    icon: 'heart-outline',
    color: '#FCE4EC',
    bgColor: '#C62828',
    products: 85,
    desc: 'Cardiovascular wellness',
    type: 'chronic',
    description: 'Protect your heart with our premium cardiac care products. From BP monitors to cholesterol management, we have everything for heart health.',
    bannerImage: 'heart_banner',
    features: ['BP Monitoring', 'Cholesterol Management', 'Heart Medicines', 'Cardiac Diet'],
    products: [
      { id: 'h1', name: 'BP Monitor Omron', brand: 'Omron', price: 1499, mrp: 1999, rating: 4.8, discount: '25% OFF' },
      { id: 'h2', name: 'Atorva 20mg', brand: 'Zydus', price: 180, mrp: 220, rating: 4.6, discount: '18% OFF' },
      { id: 'h3', name: 'ECG Machine', brand: 'Philips', price: 2999, mrp: 3999, rating: 4.7, discount: '25% OFF' },
      { id: 'h4', name: 'Aspirin 75mg', brand: 'Bayer', price: 25, mrp: 35, rating: 4.7, discount: '28% OFF' },
      { id: 'h5', name: 'Cardiostam 5mg', brand: 'USV', price: 120, mrp: 150, rating: 4.5, discount: '20% OFF' },
      { id: 'h6', name: 'Omega 3 Fish Oil', brand: 'Himalaya', price: 349, mrp: 499, rating: 4.6, discount: '30% OFF' },
    ],
    tips: [
      'Monitor BP regularly',
      'Reduce sodium intake',
      'Exercise at least 30 minutes daily',
      'Avoid smoking and alcohol',
    ],
    expertTips: [
      { title: 'Foods for a Healthy Heart', readTime: '5 min', category: 'Nutrition' },
      { title: 'Understanding Cholesterol Numbers', readTime: '4 min', category: 'Diagnosis' },
      { title: 'Heart-Exercise Guidelines', readTime: '6 min', category: 'Fitness' },
    ],
    faqs: [
      { q: 'What is normal BP?', a: '120/80 mmHg is considered normal.' },
      { q: 'How to lower cholesterol naturally?', a: 'Diet, exercise, and weight management help.' },
    ],
  },
  {
    id: 'acidity-gas',
    name: 'Acidity & Gas',
    icon: 'flame-outline',
    color: '#FFF3E0',
    bgColor: '#EF6C00',
    products: 65,
    desc: 'Digestive comfort solutions',
    type: 'lifestyle',
    description: 'Find relief from acidity and digestive issues with our range of antacids, PPIs, and digestive supplements. Say goodbye to heartburn and bloating.',
    bannerImage: 'acidity_banner',
    features: ['Fast Relief', 'Long-lasting Action', 'Doctor Recommended'],
    products: [
      { id: 'ac1', name: 'Pantoprazole 40mg', brand: 'Sun Pharma', price: 85, mrp: 100, rating: 4.6, discount: '15% OFF' },
      { id: 'ac2', name: 'Gelusil Syrup', brand: 'Pfizer', price: 120, mrp: 150, rating: 4.5, discount: '20% OFF' },
      { id: 'ac3', name: 'Eno Regular', brand: 'GSK', price: 30, mrp: 40, rating: 4.4, discount: '25% OFF' },
      { id: 'ac4', name: 'Digene Gel', brand: 'Abbott', price: 90, mrp: 120, rating: 4.5, discount: '25% OFF' },
      { id: 'ac5', name: 'Omez 20mg', brand: 'Dr Reddy', price: 65, mrp: 80, rating: 4.6, discount: '18% OFF' },
      { id: 'ac6', name: 'Gas-O-Fast', brand: 'Ajanta', price: 25, mrp: 35, rating: 4.4, discount: '28% OFF' },
    ],
    tips: [
      'Avoid spicy and oily foods',
      'Eat smaller, frequent meals',
      'Don\'t lie down after eating',
      'Maintain healthy weight',
    ],
    expertTips: [
      { title: 'Diet for Acidity Relief', readTime: '4 min', category: 'Nutrition' },
      { title: 'Understanding GERD', readTime: '5 min', category: 'Condition' },
    ],
    faqs: [
      { q: 'Why do I get acidity?', a: 'Various reasons including diet, stress, medications.' },
      { q: 'Is acidity serious?', a: 'Chronic acidity needs medical attention.' },
    ],
  },
  {
    id: 'joint-bone',
    name: 'Joint & Bone',
    icon: 'body-outline',
    color: '#F3E5F5',
    bgColor: '#7B1FA2',
    products: 90,
    desc: 'Mobility & bone strength',
    type: 'chronic',
    description: 'Support your joints and bones with our comprehensive range of supplements and pain relief products. Stay mobile and active.',
    bannerImage: 'joint_banner',
    features: ['Pain Relief', 'Joint Support', 'Bone Health', 'Mobility Aids'],
    products: [
      { id: 'j1', name: 'Shelcal 500mg', brand: 'Torrent', price: 115, mrp: 135, rating: 4.5, discount: '15% OFF' },
      { id: 'j2', name: 'Glucosamine tablets', brand: 'Himalaya', price: 250, mrp: 320, rating: 4.6, discount: '21% OFF' },
      { id: 'j3', name: 'Calcium Sandoz', brand: 'Novartis', price: 180, mrp: 220, rating: 4.5, discount: '18% OFF' },
      { id: 'j4', name: 'Volini Spray', brand: 'Sun Pharma', price: 179, mrp: 250, rating: 4.6, discount: '28% OFF' },
      { id: 'j5', name: 'Iodex', brand: 'GSK', price: 45, mrp: 55, rating: 4.4, discount: '18% OFF' },
      { id: 'j6', name: 'Chondroitin Sulfate', brand: 'Usv', price: 350, mrp: 450, rating: 4.5, discount: '22% OFF' },
    ],
    tips: [
      'Maintain adequate calcium intake',
      'Exercise regularly for joint flexibility',
      'Maintain healthy weight',
      'Use joint supplements preventively',
    ],
    expertTips: [
      { title: 'Best Exercises for Joints', readTime: '5 min', category: 'Fitness' },
      { title: 'Calcium-Rich Foods', readTime: '4 min', category: 'Nutrition' },
    ],
    faqs: [
      { q: 'When should I take calcium?', a: 'With meals for better absorption.' },
      { q: 'Are joint supplements effective?', a: 'Yes, with consistent use.' },
    ],
  },
  {
    id: 'cold-cough',
    name: 'Cold & Cough',
    icon: 'snow-outline',
    color: '#E1F5FE',
    bgColor: '#0288D1',
    products: 75,
    desc: 'Respiratory relief',
    type: 'seasonal',
    description: 'Find relief from cold and cough with our effective medicines and supplements. Quick recovery solutions for you and your family.',
    bannerImage: 'cold_cough_banner',
    features: ['Fast Relief', 'Non-Drowsy Options', 'For All Ages'],
    products: [
      { id: 'cc1', name: 'Crocin Cold & Flu', brand: 'GSK', price: 45, mrp: 55, rating: 4.5, discount: '18% OFF' },
      { id: 'cc2', name: 'Benadryl Syrup', brand: 'Johnson', price: 120, mrp: 150, rating: 4.6, discount: '20% OFF' },
      { id: 'cc3', name: 'Aspirin Complex', brand: 'Bayer', price: 60, mrp: 75, rating: 4.4, discount: '20% OFF' },
      { id: 'cc4', name: 'Cheston Cold', brand: 'Cipla', price: 35, mrp: 45, rating: 4.3, discount: '22% OFF' },
      { id: 'cc5', name: 'Zyncet Tablet', brand: 'Lupin', price: 40, mrp: 50, rating: 4.5, discount: '20% OFF' },
      { id: 'cc6', name: 'Vicks Vaporub', brand: 'P&G', price: 80, mrp: 100, rating: 4.7, discount: '20% OFF' },
    ],
    tips: [
      'Stay hydrated',
      'Rest properly',
      'Use steam inhalation',
      'Vitamin C helps quick recovery',
    ],
    expertTips: [
      { title: 'Home Remedies for Cold', readTime: '4 min', category: 'Tips' },
      { title: 'When to See a Doctor', readTime: '3 min', category: 'Advice' },
    ],
    faqs: [
      { q: 'How long does cold last?', a: 'Usually 7-10 days.' },
      { q: 'Is cold contagious?', a: 'Yes, especially in first few days.' },
    ],
  },
  {
    id: 'immunity',
    name: 'Immunity',
    icon: 'shield-outline',
    color: '#E8F5E9',
    bgColor: '#2E7D32',
    products: 110,
    desc: 'Strengthen your defense',
    type: 'lifestyle',
    description: 'Boost your immune system with our premium immunity products. From vitamins to herbal supplements, strengthen your body\'s natural defense.',
    bannerImage: 'immunity_banner',
    features: ['Natural Ingredients', 'Doctor Recommended', 'For All Ages'],
    products: [
      { id: 'im1', name: 'Vitamin C 1000mg', brand: 'Limca', price: 150, mrp: 199, rating: 4.6, discount: '25% OFF' },
      { id: 'im2', name: 'Chyawanprash', brand: 'Dabur', price: 350, mrp: 450, rating: 4.8, discount: '22% OFF' },
      { id: 'im3', name: 'Zincovit', brand: 'Apex', price: 180, mrp: 220, rating: 4.5, discount: '18% OFF' },
      { id: 'im4', name: 'Ashwagandha', brand: 'Himalaya', price: 250, mrp: 320, rating: 4.6, discount: '21% OFF' },
      { id: 'im5', name: 'Giloy Juice', brand: 'Patanjali', price: 120, mrp: 150, rating: 4.5, discount: '20% OFF' },
      { id: 'im6', name: 'Echinacea', brand: 'Himalaya', price: 180, mrp: 230, rating: 4.4, discount: '21% OFF' },
    ],
    tips: [
      'Get adequate sleep',
      'Eat a balanced diet',
      'Exercise regularly',
      'Manage stress levels',
    ],
    expertTips: [
      { title: 'Foods That Boost Immunity', readTime: '5 min', category: 'Nutrition' },
      { title: 'Sleep and Immunity', readTime: '4 min', category: 'Lifestyle' },
    ],
    faqs: [
      { q: 'How to boost immunity naturally?', a: 'Good diet, sleep, exercise, and stress management.' },
      { q: 'When to take immunity supplements?', a: 'Especially during seasonal changes.' },
    ],
  },
  {
    id: 'skin-problems',
    name: 'Skin Problems',
    icon: 'flower-outline',
    color: '#FFF8E1',
    bgColor: '#F9A825',
    products: 95,
    desc: 'Clear & healthy skin',
    type: 'lifestyle',
    description: 'Treat your skin problems with our effective skincare solutions. From acne to anti-aging, find the right products for glowing skin.',
    bannerImage: 'skin_banner',
    features: ['Dermat Tested', 'For All Skin Types', 'Clinically Proven'],
    products: [
      { id: 'sp1', name: 'Retino A 0.025%', brand: 'J&J', price: 180, mrp: 220, rating: 4.7, discount: '18% OFF' },
      { id: 'sp2', name: 'Melasma Cream', brand: 'Galderma', price: 350, mrp: 450, rating: 4.6, discount: '22% OFF' },
      { id: 'sp3', name: 'Acne.org Gel', brand: 'Ipca', price: 120, mrp: 150, rating: 4.5, discount: '20% OFF' },
      { id: 'sp4', name: 'Candid Gel', brand: 'GSK', price: 80, mrp: 100, rating: 4.6, discount: '20% OFF' },
      { id: 'sp5', name: 'Moisturizer', brand: 'Cetaphil', price: 399, mrp: 549, rating: 4.8, discount: '27% OFF' },
      { id: 'sp6', name: 'Sunscreen SPF 50', brand: 'La Roche', price: 599, mrp: 799, rating: 4.7, discount: '25% OFF' },
    ],
    tips: [
      'Know your skin type',
      'Use sunscreen daily',
      'Maintain skincare routine',
      'Stay hydrated',
    ],
    expertTips: [
      { title: 'Skincare for Different Skin Types', readTime: '5 min', category: 'Tips' },
      { title: 'Understanding Acne', readTime: '4 min', category: 'Condition' },
    ],
    faqs: [
      { q: 'How to treat acne?', a: 'Use appropriate products and consult dermatologist.' },
      { q: 'Is sunscreen necessary daily?', a: 'Yes, even indoors.' },
    ],
  },
  {
    id: 'hair-loss',
    name: 'Hair Loss',
    icon: 'cut-outline',
    color: '#F3E5F5',
    bgColor: '#6A1B9A',
    products: 60,
    desc: 'Hair growth & care',
    type: 'lifestyle',
    description: 'Combat hair loss and promote hair growth with our effective range of hair care products. Get thicker, healthier hair.',
    bannerImage: 'hair_banner',
    features: ['Hair Growth', 'Anti-Hair Fall', 'Scalp Care', 'Hair Strengthening'],
    products: [
      { id: 'hl1', name: 'Minoxidil 5%', brand: 'Rogaine', price: 450, mrp: 550, rating: 4.5, discount: '18% OFF' },
      { id: 'hl2', name: 'Finasteride 1mg', brand: 'Cipla', price: 350, mrp: 420, rating: 4.6, discount: '16% OFF' },
      { id: 'hl3', name: 'Hair Growth Oil', brand: 'Mahashakti', price: 199, mrp: 250, rating: 4.4, discount: '20% OFF' },
      { id: 'hl4', name: 'Anti Hair Fall Shampoo', brand: 'L\'Oreal', price: 299, mrp: 399, rating: 4.5, discount: '25% OFF' },
      { id: 'hl5', name: 'Hair Serum', brand: 'Mamaearth', price: 349, mrp: 449, rating: 4.6, discount: '22% OFF' },
      { id: 'hl6', name: 'Multivitamins for Hair', brand: 'Keratrin', price: 450, mrp: 550, rating: 4.5, discount: '18% OFF' },
    ],
    tips: [
      'Massage scalp regularly',
      'Avoid heat styling',
      'Eat protein-rich food',
      'Manage stress',
    ],
    expertTips: [
      { title: 'Foods for Hair Growth', readTime: '4 min', category: 'Nutrition' },
      { title: 'Understanding Hair Loss', readTime: '5 min', category: 'Condition' },
    ],
    faqs: [
      { q: 'What causes hair loss?', a: 'Various factors including genetics, stress, nutrition.' },
      { q: 'Is hair loss reversible?', a: 'Depends on cause. Early treatment helps.' },
    ],
  },
  {
    id: 'eye-care',
    name: 'Eye Care',
    icon: 'eye-outline',
    color: '#E3F2FD',
    bgColor: '#1976D2',
    products: 40,
    desc: 'Vision & eye health',
    type: 'chronic',
    description: 'Take care of your eyes with our range of eye care products. From eye drops to supplements, protect your vision.',
    bannerImage: 'eye_banner',
    features: ['Eye Drops', 'Contact Lens Care', 'Eye Supplements', 'Vision Aids'],
    products: [
      { id: 'ec1', name: 'Refresh Tears', brand: 'Allergan', price: 150, mrp: 180, rating: 4.6, discount: '16% OFF' },
      { id: 'ec2', name: 'Moxifloxacin Eye Drops', brand: 'Cipla', price: 80, mrp: 100, rating: 4.5, discount: '20% OFF' },
      { id: 'ec3', name: 'Lumify Eye Drops', brand: 'Bausch', price: 450, mrp: 550, rating: 4.7, discount: '18% OFF' },
      { id: 'ec4', name: 'Optometry Capsule', brand: 'Alcon', price: 250, mrp: 320, rating: 4.5, discount: '21% OFF' },
      { id: 'ec5', name: 'Contact Lens Solution', brand: 'Bausch', price: 299, mrp: 399, rating: 4.6, discount: '25% OFF' },
      { id: 'ec6', name: 'Eye Vitamin Supplement', brand: 'Sil', price: 350, mrp: 450, rating: 4.5, discount: '22% OFF' },
    ],
    tips: [
      'Take regular breaks from screen',
      'Get eye checkups regularly',
      'Wear sunglasses outdoors',
      'Maintain healthy diet',
    ],
    expertTips: [
      { title: 'Computer Vision Syndrome', readTime: '4 min', category: 'Condition' },
      { title: 'Eye-Healthy Foods', readTime: '5 min', category: 'Nutrition' },
    ],
    faqs: [
      { q: 'How often should I get eye checkup?', a: 'At least once a year.' },
      { q: 'Are eye drops safe for daily use?', a: 'Depends on type. Consult doctor.' },
    ],
  },
  {
    id: 'thyroid',
    name: 'Thyroid',
    icon: 'fitness-outline',
    color: '#E0F2F1',
    bgColor: '#00796B',
    products: 35,
    desc: 'Thyroid management',
    type: 'chronic',
    description: 'Manage thyroid conditions effectively with our range of thyroid medicines and supplements. Professional support for thyroid health.',
    bannerImage: 'thyroid_banner',
    features: ['Thyroid Medicines', 'Thyroid Supplements', 'Monitoring Devices', 'Expert Support'],
    products: [
      { id: 't1', name: 'Thyroxine 50mcg', brand: 'Lupin', price: 50, mrp: 65, rating: 4.7, discount: '23% OFF' },
      { id: 't2', name: 'Thyroxine 100mcg', brand: 'Lupin', price: 55, mrp: 70, rating: 4.7, discount: '21% OFF' },
      { id: 't3', name: 'Thyronorm 75mcg', brand: 'Mankind', price: 95, mrp: 120, rating: 4.8, discount: '20% OFF' },
      { id: 't4', name: 'Thyronorm 100mcg', brand: 'Mankind', price: 105, mrp: 130, rating: 4.8, discount: '19% OFF' },
      { id: 't5', name: 'Thyroid Support', brand: 'Himalaya', price: 180, mrp: 230, rating: 4.4, discount: '21% OFF' },
      { id: 't6', name: 'Selenium Supplement', brand: 'Solgar', price: 450, mrp: 550, rating: 4.5, discount: '18% OFF' },
    ],
    tips: [
      'Take medicine on empty stomach',
      'Regular blood tests',
      'Avoid certain foods with medicine',
      'Stay consistent with medication',
    ],
    expertTips: [
      { title: 'Thyroid and Diet', readTime: '5 min', category: 'Nutrition' },
      { title: 'Understanding Thyroid Tests', readTime: '4 min', category: 'Diagnosis' },
    ],
    faqs: [
      { q: 'How to take thyroid medicine?', a: 'On empty stomach, 30-60 min before breakfast.' },
      { q: 'Can thyroid be cured?', a: 'Managed effectively with medication.' },
    ],
  },
];

export const getConcernById = (id) => {
  return CONCERNS_DATA.find(concern => concern.id === id);
};

export const getAllConcerns = () => {
  return CONCERNS_DATA;
};
