/**
 * Medicine Data for Detail Pages
 * Contains all medicine information for generating unique detail pages
 */

export const MEDICINES_DATA = [
  {
    id: 'dolo-650',
    name: 'Dolo 650mg Tablet',
    brand: 'Micro Labs',
    form: 'Strip of 15 Tablets',
    price: 32.40,
    mrp: 36.00,
    rating: 4.8,
    reviews: 12400,
    delivery: 'By 11:30 PM Today',
    prescription: false,
    bestseller: true,
    category: 'Pain Relief',
    description: 'Dolo 650 is a trusted pain reliever that provides effective relief from fever and mild to moderate pain. It contains Paracetamol which is scientifically proven to be safe and effective.',
    composition: 'Paracetamol 650mg',
    uses: ['Fever', 'Headache', 'Body pain', 'Toothache', 'Menstrual pain'],
    sideEffects: ['Nausea', 'Stomach pain', 'Loss of appetite'],
    dosage: '1 tablet 3-4 times daily or as directed by physician',
    warnings: ['Do not exceed recommended dose', 'Avoid alcohol', 'Consult doctor if pregnant'],
    images: ['dolo_650'],
    alternatives: ['Crocin 500mg', 'Calpol 650mg', 'Sumo 650mg'],
    relatedProducts: ['Dolo 500mg', 'Dolo 650 Syrup', 'Dolo Suppository'],
    faqs: [
      { q: 'Is Dolo 650 safe for long term use?', a: 'Dolo 650 should not be used for more than 10 days for pain without consulting a doctor.' },
      { q: 'Can I take Dolo 650 on empty stomach?', a: 'It is best to take after food to avoid stomach irritation.' },
      { q: 'Is Dolo 650 habit forming?', a: 'No, Dolo 650 is not habit forming.' },
    ],
    reviews: [
      { user: 'Rahul S.', rating: 5, comment: 'Very effective for fever', date: '2 days ago' },
      { user: 'Priya M.', rating: 4, comment: 'Works well for headache', date: '1 week ago' },
    ],
  },
  {
    id: 'crocin-advance',
    name: 'Crocin Advance 500mg',
    brand: 'GSK Pharma',
    form: 'Strip of 20 Tablets',
    price: 28.60,
    mrp: 34.00,
    rating: 4.7,
    reviews: 8900,
    delivery: 'By 11:30 PM Today',
    prescription: false,
    bestseller: true,
    category: 'Pain Relief',
    description: 'Crocin Advance provides fast and effective relief from pain and fever. Its unique formulation ensures quick absorption for faster action.',
    composition: 'Paracetamol 500mg',
    uses: ['Fever', 'Headache', 'Body ache', 'Cold & Flu symptoms'],
    sideEffects: ['Skin rash', 'Dizziness', 'Nausea'],
    dosage: '1-2 tablets every 4-6 hours',
    warnings: ['Keep out of reach of children', 'Do not overdose'],
    images: ['crocin_advance'],
    alternatives: ['Dolo 650', 'Calpol 500', 'Pyridium 500'],
    relatedProducts: ['Crocin DS Syrup', 'Crocin Pain Relief', 'Crocin 650'],
    faqs: [
      { q: 'How fast does Crocin Advance work?', a: 'It starts working within 15-30 minutes of consumption.' },
      { q: 'Can I give Crocin Advance to children?', a: 'Yes, but in appropriate pediatric dosage. Consult doctor.' },
    ],
    reviews: [
      { user: 'Amit K.', rating: 5, comment: 'Quick relief from fever', date: '3 days ago' },
    ],
  },
  {
    id: 'shelcal-500',
    name: 'Shelcal 500mg Tablet',
    brand: 'Torrent Pharma',
    form: 'Strip of 15 Tablets',
    price: 114.80,
    mrp: 135.00,
    rating: 4.5,
    reviews: 5600,
    delivery: 'By Tomorrow 10 AM',
    prescription: false,
    bestseller: false,
    category: 'Vitamins & Supplements',
    description: 'Shelcal 500mg provides Calcium and Vitamin D3 which are essential for strong bones and teeth. It helps prevent osteoporosis and maintains bone health.',
    composition: 'Calcium Carbonate 500mg, Vitamin D3 250IU',
    uses: ['Calcium deficiency', 'Bone health', 'Osteoporosis', 'Postmenopausal health'],
    sideEffects: ['Constipation', 'Gas', 'Nausea'],
    dosage: '1 tablet twice daily with food',
    warnings: ['Do not exceed dose', 'Kidney disease patients consult doctor'],
    images: ['shelcal_500'],
    alternatives: ['Ostocalcium Plus', 'Calcirol', 'Calshine'],
    relatedProducts: ['Shelcal 250mg', 'Shelcal Gold', 'Shelcal HD'],
    faqs: [
      { q: 'When is the best time to take Shelcal?', a: 'Take after meals for better absorption.' },
      { q: 'Can I take Shelcal with other medicines?', a: 'Maintain 2-hour gap with other medications.' },
    ],
    reviews: [
      { user: 'Sunita R.', rating: 5, comment: 'Good for bone health', date: '1 month ago' },
    ],
  },
  {
    id: 'pan-40',
    name: 'Pan 40mg Tablet',
    brand: 'Alkem Labs',
    form: 'Strip of 15 Tablets',
    price: 78.50,
    mrp: 92.00,
    rating: 4.6,
    reviews: 7800,
    delivery: 'By 11:30 PM Today',
    prescription: true,
    bestseller: false,
    category: 'Gastric Issues',
    description: 'Pan 40mg is a proton pump inhibitor that effectively reduces stomach acid production. It provides relief from acid reflux, heartburn, and gastritis.',
    composition: 'Pantoprazole 40mg',
    uses: ['Acid reflux', 'GERD', 'Peptic ulcer', 'Gastritis', 'Zollinger-Ellison syndrome'],
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Abdominal pain'],
    dosage: '1 tablet once daily before breakfast',
    warnings: ['May interact with other medicines', 'Long term use requires monitoring'],
    images: ['pan_40'],
    alternatives: ['Pantocid 40mg', 'Pantosec 40mg', 'Panlip 40mg'],
    relatedProducts: ['Pan 20mg', 'Pan Injection', 'Pan Oral Suspension'],
    faqs: [
      { q: 'How long can I take Pan 40mg?', a: 'Usually 2-4 weeks for acid-related conditions. Long term use should be under doctor supervision.' },
      { q: 'Can I take Pan 40mg with food?', a: 'Take on empty stomach, 30 minutes before breakfast.' },
    ],
    reviews: [
      { user: 'Vijay L.', rating: 4, comment: 'Effective for acidity', date: '2 weeks ago' },
    ],
  },
  {
    id: 'azithromycin-500',
    name: 'Azithromycin 500mg',
    brand: 'Cipla',
    form: 'Strip of 3 Tablets',
    price: 67.20,
    mrp: 79.00,
    rating: 4.4,
    reviews: 6200,
    delivery: 'By Tomorrow 10 AM',
    prescription: true,
    bestseller: false,
    category: 'Antibiotics',
    description: 'Azithromycin is a macrolide antibiotic used to treat various bacterial infections including respiratory infections, skin infections, and ear infections.',
    composition: 'Azithromycin 500mg',
    uses: ['Respiratory infections', 'Skin infections', 'Ear infections', 'Sexually transmitted diseases'],
    sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain', 'Headache'],
    dosage: 'As directed by physician, usually 1 tablet daily',
    warnings: ['Complete full course', 'May cause heart rhythm issues'],
    images: ['azithro_500'],
    alternatives: ['Zithromax', 'Azee 500', 'Azithral 500'],
    relatedProducts: ['Azithromycin 250mg', 'Azithromycin Suspension', 'Azithromycin DS'],
    faqs: [
      { q: 'Can I take Azithromycin with milk?', a: 'Avoid dairy products 2 hours before and after taking.' },
      { q: 'Is Azithromycin effective for cold?', a: 'No, it only works against bacterial infections, not viral colds.' },
    ],
    reviews: [
      { user: 'Ravi P.', rating: 4, comment: 'Worked well for infection', date: '1 week ago' },
    ],
  },
  {
    id: 'vitamin-d3-60k',
    name: 'Vitamin D3 60K IU',
    brand: 'USV Limited',
    form: 'Strip of 4 Capsules',
    price: 120.00,
    mrp: 150.00,
    rating: 4.9,
    reviews: 15000,
    delivery: 'By 11:30 PM Today',
    prescription: false,
    bestseller: true,
    category: 'Vitamins & Supplements',
    description: 'Vitamin D3 60K IU helps maintain optimal vitamin D levels in the body. It supports bone health, immune function, and overall wellbeing.',
    composition: 'Cholecalciferol 60,000 IU',
    uses: ['Vitamin D deficiency', 'Bone health', 'Immune support', 'Muscle strength'],
    sideEffects: ['Hypercalcemia (if overdosed)', 'Nausea', 'Weakness'],
    dosage: '1 capsule weekly for 8-12 weeks or as directed',
    warnings: ['Do not exceed recommended dose', 'Monitor blood levels'],
    images: ['vit_d3_60k'],
    alternatives: ['Calcirol 60K', 'D-Rise 60K', 'Solu D 60K'],
    relatedProducts: ['Vitamin D3 1000IU', 'Vitamin D3 2000IU', 'D3 Max'],
    faqs: [
      { q: 'When should I take Vitamin D3?', a: 'Take with a fatty meal for better absorption.' },
      { q: 'Can I take Vitamin D3 daily?', a: 'Daily lower doses (1000-2000IU) or weekly high dose (60K) as per doctor advice.' },
    ],
    reviews: [
      { user: 'Anjali S.', rating: 5, comment: 'Great for vitamin D deficiency', date: '1 day ago' },
    ],
  },
  {
    id: 'cetirizine-10mg',
    name: 'Cetirizine 10mg',
    brand: 'Dr Reddys',
    form: 'Strip of 10 Tablets',
    price: 18.50,
    mrp: 22.00,
    rating: 4.3,
    reviews: 4500,
    delivery: 'By 11:30 PM Today',
    prescription: false,
    bestseller: false,
    category: 'Allergy',
    description: 'Cetirizine is an antihistamine that provides relief from allergic symptoms like sneezing, runny nose, itching, and watery eyes.',
    composition: 'Cetirizine Hydrochloride 10mg',
    uses: ['Allergic rhinitis', 'Urticaria', 'Itching', 'Cold symptoms'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Fatigue', 'Headache'],
    dosage: '1 tablet once daily',
    warnings: ['May cause drowsiness', 'Avoid driving after taking'],
    images: ['cetirizine_10'],
    alternatives: ['Reactine 10mg', 'Allercet 10mg', 'Cetzine 10mg'],
    relatedProducts: ['Cetirizine 5mg', 'Cetirizine Syrup', 'Cetirizine M'],
    faqs: [
      { q: 'Does Cetirizine make you sleepy?', a: 'It may cause drowsiness in some people.' },
      { q: 'Can I take Cetirizine twice a day?', a: 'Usually once daily is sufficient. Do not exceed recommended dose.' },
    ],
    reviews: [
      { user: 'Kiran M.', rating: 4, comment: 'Good for allergies', date: '5 days ago' },
    ],
  },
  {
    id: 'amoxicillin-500',
    name: 'Amoxicillin 500mg',
    brand: 'Cipla',
    form: 'Strip of 15 Capsules',
    price: 89.00,
    mrp: 105.00,
    rating: 4.5,
    reviews: 7100,
    delivery: 'By Tomorrow 10 AM',
    prescription: true,
    bestseller: false,
    category: 'Antibiotics',
    description: 'Amoxicillin is a penicillin-type antibiotic used to treat a wide range of bacterial infections including respiratory, ear, throat, and urinary tract infections.',
    composition: 'Amoxicillin Trihydrate 500mg',
    uses: ['Respiratory infections', 'Ear infections', 'UTI', 'Skin infections'],
    sideEffects: ['Nausea', 'Vomiting', 'Diarrhea', 'Rash'],
    dosage: 'As directed by physician, usually 1 capsule 3 times daily',
    warnings: ['Penicillin allergy patients avoid', 'Complete full course'],
    images: ['amox_500'],
    alternatives: ['Novamox 500', 'Mox 500', 'Wymox 500'],
    relatedProducts: ['Amoxicillin 250mg', 'Amoxicillin Suspension', 'Augmentin'],
    faqs: [
      { q: 'Can I take Amoxicillin with milk?', a: 'Yes, but dairy may slightly reduce absorption.' },
      { q: 'Does Amoxicillin affect birth control?', a: 'It may reduce effectiveness of oral contraceptives.' },
    ],
    reviews: [
      { user: 'Deepak T.', rating: 4, comment: 'Effective antibiotic', date: '3 days ago' },
    ],
  },
  {
    id: 'pantoprazole-40mg',
    name: 'Pantoprazole 40mg',
    brand: 'Sun Pharma',
    form: 'Strip of 15 Tablets',
    price: 85.00,
    mrp: 100.00,
    rating: 4.6,
    reviews: 5800,
    delivery: 'By 11:30 PM Today',
    prescription: true,
    bestseller: false,
    category: 'Gastric Issues',
    description: 'Pantoprazole 40mg is a proton pump inhibitor that reduces stomach acid production and provides relief from acid-related disorders.',
    composition: 'Pantoprazole Sodium 40mg',
    uses: ['GERD', 'Acid reflux', 'Peptic ulcer', 'Erosive esophagitis'],
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Flatulence'],
    dosage: '1 tablet once daily before breakfast',
    warnings: ['Long term use may cause vitamin B12 deficiency'],
    images: ['panto_40'],
    alternatives: ['Pan 40mg', 'Pantocid 40mg', 'Pantosec 40mg'],
    relatedProducts: ['Pantoprazole 20mg', 'Pantoprazole Injection', 'Pantoprazole Sachet'],
    faqs: [
      { q: 'How long to take Pantoprazole?', a: 'Usually 4-8 weeks for ulcer, may be longer for GERD.' },
      { q: 'Can I stop Pantoprazole suddenly?', a: 'Do not stop without consulting doctor.' },
    ],
    reviews: [
      { user: 'Meena K.', rating: 5, comment: 'Best for acidity', date: '1 week ago' },
    ],
  },
  {
    id: 'metformin-500mg',
    name: 'Metformin 500mg',
    brand: 'USV Limited',
    form: 'Strip of 20 Tablets',
    price: 25.00,
    mrp: 32.00,
    rating: 4.7,
    reviews: 9200,
    delivery: 'By Tomorrow 10 AM',
    prescription: true,
    bestseller: true,
    category: 'Diabetes',
    description: 'Metformin is the first-line medication for type 2 diabetes. It helps control blood sugar levels and improves insulin sensitivity.',
    composition: 'Metformin Hydrochloride 500mg',
    uses: ['Type 2 Diabetes', 'PCOS', 'Weight management in diabetes'],
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset', 'Metallic taste'],
    dosage: 'As directed by physician, usually 1 tablet with meals',
    warnings: ['Monitor kidney function', 'Avoid in liver disease'],
    images: ['met_500'],
    alternatives: ['Glyciphage 500mg', 'Gluformin 500mg', 'Obimet 500mg'],
    relatedProducts: ['Metformin 250mg', 'Metformin XR 500mg', 'Metformin 1000mg'],
    faqs: [
      { q: 'When should I take Metformin?', a: 'Take with meals to reduce stomach upset.' },
      { q: 'Does Metformin cause weight loss?', a: 'It may cause mild weight loss in some patients.' },
    ],
    reviews: [
      { user: 'Suresh R.', rating: 5, comment: 'Essential for diabetes control', date: '4 days ago' },
    ],
  },
];

export const getMedicineById = (id) => {
  return MEDICINES_DATA.find(med => med.id === id);
};

export const getAllMedicines = () => {
  return MEDICINES_DATA;
};
